spring:
  application:
    name: chatapi
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    locations: classpath:/db/migration
    schemas: chatapi
    baselineOnMigrate: true
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chatapi?currentSchema=chatapi
    username: postgres
    password: ${DATABASE_PASSWORD}