spring.config.import: optional:secrets.properties
spring.application.name: chatapi
spring.jackson.property-naming-strategy: SNAKE_CASE
spring.flyway.locations: classpath:/db/migration
spring.flyway.schemas: chatapi
spring.flyway.baselineOnMigrate: true
spring.flyway.enabled: true
spring.datasource.driverClassName: org.postgresql.Driver
